

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBlock;
            }
        }
    }
}

namespace BlackjackClient
{
    partial ref class PlayerSpace : public ::Windows::UI::Xaml::Controls::UserControl, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::Controls::Grid^ playerCardGrid;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ playerName;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ playerBalance;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ playerBet;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ playerInsurance;
    };
}

