

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBox;
                ref class TextBlock;
            }
        }
    }
}

namespace WindowsLiveAuth
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Button^ LogInButton;
        private: ::Windows::UI::Xaml::Controls::Button^ GetInfoButton;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Box1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Block1;
        private: ::Windows::UI::Xaml::Controls::Button^ LogOutButton;
        private: ::Windows::UI::Xaml::Controls::Button^ UploadButton;
        private: ::Windows::UI::Xaml::Controls::Button^ DownloadButton;
    };
}

